modLoader="javafml"
loaderVersion="[43,)"
license="MIT"
[[mods]]
modId="mekaweapons"
version="${mod_version}"
displayName="Mekanism: Weapons"
authors="oMeranha"
description='''Weapons for Mekanism.'''
[[dependencies.mekaweapons]]
	modId="forge"
	mandatory=true
	versionRange="[43,)"
	ordering="NONE"
	side="BOTH"
[[dependencies.mekaweapons]]
	modId="minecraft"
	mandatory=true
	versionRange="1.19.2"
	ordering="NONE"
	side="BOTH"
[[dependencies.mekaweapons]]
	modId="mekanism"
	mandatory=true
	versionRange="10.3.9.13"
	ordering="AFTER"
	side="BOTH"
